Repository proj-poppin/poppin-app, pull requests merged in 2024-05, with the labels that each got.

#31 Fix - 앱전반에 걸친 버그 수정
  src/apis/auth/basicLogin.ts
  src/apis/axios.ts
  src/components/HomeLoginHeader.tsx
  src/hooks/useAppleLogin.tsx
  src/hooks/useGoogleLogin.tsx
  src/hooks/useKakaoLogin.tsx
  src/hooks/useNaverLogin.tsx
  src/hooks/useSetAccessToken.ts
  src/hooks/useSetAccessTokenAndRefreshToken.ts
  src/hooks/useSignUp.tsx
  src/hooks/useSocialSignUp.tsx
  src/navigators/RootNavigator.tsx
  src/utils/function/setAccessTokenAndRefreshToken.ts
Labels: 🛠️fix 🛠️, 🚨big-issue🚨, 🚑hot-fix 🚑, 👨🏻‍💻도형👨🏻‍💻

#32 Bug/#30
  src/apis/axios.ts
  src/hooks/useBasicLogin.tsx
  src/hooks/useGoogleLogin.tsx
  src/hooks/useKakaoLogin.tsx
  src/hooks/useLogout.tsx
  src/hooks/useNaverLogin.tsx
  src/navigators/AppNavigator.tsx
  src/navigators/RootNavigator.tsx
  src/pages/home/HomeScreen.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/preference/PreferenceScreen.tsx
Labels: 🛠️fix 🛠️, 🧑🏻‍💻동혁🧑🏻‍💻

#34 ✨Feat: 알림, 공지사항 UI 구현
  App.tsx
  ios/GoogleService-Info.plist
  ios/Podfile.lock
  ios/PoppinProject.xcodeproj/project.pbxproj
  ios/PoppinProject/Info.plist
  ios/PoppinProject/PoppinProject.entitlements
  package-lock.json
  package.json
  src/assets/icons/setting.svg
  src/components/HomeLoginHeader.tsx
  src/components/alarm/AlarmCard.tsx
  src/components/alarm/SettingSwitch.tsx
  src/components/molecules/card/HotListCard.tsx
  src/components/molecules/card/RowPopUpCard.tsx
  src/components/organisms/header/HomeHeader.tsx
  src/hooks/useLogout.tsx
  src/navigators/AppNavigator.tsx
  src/navigators/RootNavigator.tsx
  src/navigators/options/AlarmOptions.tsx
  src/navigators/options/AlarmSettingOptions.tsx
  src/navigators/options/NoticeDetailOptions.tsx
  src/pages/Alarm/AlaramSettingScreen.tsx
  src/pages/Alarm/AlarmScreen.tsx
  src/pages/Alarm/dummyData.tsx
  src/pages/Notice/NoticeDetailScreen.tsx
  src/pages/home/HomeScreen.tsx
  src/types/AppNavigatorParamList.ts
  yarn.lock
Labels: 💄ui/ux💄, ✨ feature ✨, 👩🏻‍💻소희👩🏻‍💻

#35 ✨Feat: 팝업찾기 UI 구현
  ios/GoogleService-Info.plist
  src/assets/icons/inputCancel.svg
  src/assets/images/noKeyword.svg
  src/assets/images/searchInput.svg
  src/components/CustomDropDown.tsx
  src/components/DividerLine.tsx
  src/components/alarm/AlarmCard.tsx
  src/components/findPopup/FindCard.tsx
  src/components/findPopup/FindFilterBackdrop.tsx
  src/components/findPopup/PopupTag.tsx
  src/components/findPopup/constants.ts
  src/components/findPopup/dummydata.ts
  src/components/findPopup/tabs/ClosedTab.tsx
  src/components/findPopup/tabs/OperationTab.tsx
  src/components/findPopup/tabs/UpcomingTab.tsx
  src/components/molecules/card/HotListCard.tsx
  src/components/molecules/card/SampleInterestPopUpCard.tsx
  src/navigators/AppNavigator.tsx
  src/navigators/options/AlarmOptions.tsx
  src/pages/find/FindInputScreen.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/dummydata.ts
  src/pages/home/HomeScreen.tsx
  src/styles/color/globalColors.ts
  src/types/AppNavigatorParamList.ts
  src/types/NavigateOptions.ts
  src/types/alarm/AlarmCard.ts
Labels: 💄ui/ux💄, ✨ feature ✨, 🛠️fix 🛠️, 👩🏻‍💻소희👩🏻‍💻

#38 ✨Feat: 팝업상세 UI,State 처리 완료, BottomSheet 버그 수정
  ios/Podfile.lock
  ios/PoppinProject.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/user/getUser.ts
  src/assets/detail/likesReview.svg
  src/assets/detail/reviewProfile.svg
  src/assets/detail/verifiedReview.svg
  src/assets/detail/writeReview.svg
  src/assets/icons/categoryButtonClose.svg
  src/components/HomeLoginHeader.tsx
  src/components/HorizontalBarChart.tsx
  src/components/ReasonItem.tsx
  src/components/SvgWithNameBoxLabel.tsx
  src/components/UnderlineTextButton.tsx
  src/components/atoms/button/FilterSettingButton.tsx
  src/components/findPopup/CategorySelectButton.tsx
  src/components/findPopup/FindCard.tsx
  src/components/findPopup/PopupTag.tsx
  src/components/findPopup/dummydata.ts
  src/components/findPopup/percentageButton.tsx
  src/components/molecules/card/HotListCard.tsx
  src/components/organisms/VerticalDividerLine.tsx
  src/hooks/useBooleanState.tsx
  src/hooks/useLogout.tsx
  src/navigators/AppNavigator.tsx
  src/navigators/AuthNavigator.tsx
  src/navigators/RootNavigator.tsx
  src/pages/alarm/AlaramSettingScreen.tsx
  src/pages/alarm/AlarmScreen.tsx
  src/pages/alarm/dummyData.tsx
  src/pages/detail/DetailScreen.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/tabs/ClosedTab.tsx
  src/pages/find/tabs/OperationTab.tsx
  src/pages/find/tabs/UpcomingTab.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/myPage/UserRegisterScreen.tsx
  src/styles/color/globalColors.ts
  src/styles/texts/body_large/Text18M.ts
  src/styles/texts/body_medium_large/Text16B.ts
  src/styles/texts/body_medium_large/Text16M.ts
  src/styles/texts/body_medium_large/Text16R.ts
  yarn.lock
Labels: 💄ui/ux💄, ✨ feature ✨, 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻

#40 ✨Feat: 팝업찾기 API 연결
  src/apis/popup/findPopupList.ts
  src/assets/images/findPopupNoList.svg
  src/assets/images/findPopupText.svg
  src/components/findPopup/FindCard.tsx
  src/components/findPopup/constants.ts
  src/hooks/findpopup/useGetFindPopupList.tsx
  src/pages/find/FindInputScreen.tsx
  src/pages/find/FindPopupTab.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/dummydata.ts
  src/pages/find/tab/ClosedTab.tsx
  src/pages/find/tab/NotyetTab.tsx
  src/pages/find/tab/OperatonTab.tsx
  src/types/DetaiPopUpData.ts
Labels: 💄ui/ux💄, ✨ feature ✨, 👩🏻‍💻소희👩🏻‍💻

#45 🐛Bug: 앱 네비게이션 버그 수정
  src/apis/apiInstance/NonPublicApiInstance.ts
  src/apis/apiInstance/performLogout.tsx
  src/apis/auth/basicSignUp.ts
  src/apis/auth/logout.ts
  src/apis/popup/closingList.ts
  src/apis/popup/detailPopUp.ts
  src/apis/popup/findPopupList.ts
  src/apis/public/detailPopUpPublic.ts
  src/hooks/detailPopUp/useGetDetailPopUp.tsx
  src/hooks/login/useAppleLogin.tsx
  src/navigators/RootNavigator.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/home/HomeScreen.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/types/DetailPopUpDataNonPublic.ts
Labels: 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻

#47 🐛Bug: 키워드 텍스트 로직 수정
  src/components/findPopup/CategorySelectButton.tsx
  src/pages/find/FindInputScreen.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/tab/NotyetTab.tsx
Labels: 👩🏻‍💻소희👩🏻‍💻
