Repository proj-poppin/poppin-app, pull requests merged in 2024-07, with the labels that each got.

#82 ✨Feature - 프로필 이미지쪽 코드 수정
  src/apis/myPage/deleteProfileImage.ts
  src/assets/detail/reviewProfile.svg
  src/hooks/myPage/usePatchUserSetting.tsx
  src/hooks/myPage/usedeleteProfileImage.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/myPage/ProfileEditScreen.tsx
  src/types/DetailPopUpDataNonPublic.ts
Labels: ✨ feature ✨, 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻

#83 ✨Feature - 홈 알람 빨간점, 아이콘뱃지 기능추가 (#59)
  src/apis/alarm/getAlarmSettings.ts
  src/apis/alarm/getAlarmStatus.ts
  src/components/HomeLoginHeader.tsx
  src/components/organisms/header/HomeHeader.tsx
  src/hooks/alarm/useGetAlarmSettings.ts
  src/hooks/alarm/useGetAlarmStatus.ts
  src/pages/alarm/AlarmScreen.tsx
Labels: ✨ feature ✨

#86 ✨Feature - 팝업알람 디테일 API 분기처리, 공지알람 디테일 API 수정 (#85)
  src/apis/alarm/getNoticeDetail.ts
  src/apis/popup/detailPopUp.ts
  src/apis/public/detailPopUpPublic.ts
  src/components/alarm/AlarmCard.tsx
  src/hooks/detailPopUp/useGetDetailPopUp.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/types/AppNavigatorParamList.ts
Labels: ✨ feature ✨, 👨🏻‍💻민우👨🏻‍💻
