Repository proj-poppin/poppin-app, pull requests merged in 2024-06, with the labels that each got.

#53 🐛Bug: DetailPage UI 에러 수정
  src/navigators/options/PopUpDetailOptions.tsx
  src/pages/detail/PopUpDetailScreen.tsx
Labels: 💄ui/ux💄, 🛠️fix 🛠️, 👩🏻‍💻소희👩🏻‍💻

#55 ✨Feat: 팝업 캘린더 구현
  src/assets/likes/VButton.svg
  src/assets/likes/likeDummy.png
  src/pages/likes/LikeCalendarComponent.tsx
  src/pages/likes/LikeCalendarView.tsx
  src/pages/likes/LikesScreen.tsx
  src/pages/likes/calendar/CalendarComponent.tsx
  src/pages/likes/calendar/FullCalendarComponent.tsx
  src/pages/likes/calendar/HeaderTitle.tsx
  src/pages/likes/calendar/NormalCalendarComponent.tsx
Labels: ✨ feature ✨, 👨🏻‍💻민우👨🏻‍💻

#56 Fixed/detailpage
  src/assets/icons/Vector 1.svg
  src/components/ReasonItem.tsx
  src/components/SvgWithNameBoxLabel.tsx
  src/components/atoms/toast/ToastComponent.tsx
  src/components/findPopup/percentageButton.tsx
  src/components/organisms/section/CongestionSection.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/types/DetailPopUpDataNonPublic.ts
Labels: 💄ui/ux💄, 🐛bug🐛, 👩🏻‍💻소희👩🏻‍💻

#62 ✨Feat: 후기, 팝업 수정, 제보하기 API 연결
  android/gradle.properties
  ios/Podfile.lock
  ios/PoppinProject.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/apis/apiInstance/NonPublicApiInstance.ts
  src/apis/mypage/createManagerReportPopUp.ts
  src/apis/mypage/createUserReportPopUp.ts
  src/apis/popup/createReview.tsx
  src/apis/popup/modifyPopUpInfo.ts
  src/apis/report/reportPopUp.ts
  src/apis/report/reviewReport.ts
  src/apis/user/getUser.ts
  src/assets/detail/verifiedBadge.svg
  src/components/LabelAndInputWithCloseSvg.tsx
  src/components/OperationCalendarBottomSheet.tsx
  src/components/OperationHoursBottomSheet.tsx
  src/components/PreferenceOptionButtons.tsx
  src/components/RequiredTextLabel.tsx
  src/components/TextInputWithSvgIconInRight.tsx
  src/components/TwoSelectConfirmationModal.tsx
  src/components/atoms/button/SelectButtonGroup.tsx
  src/components/operatorRequest/PostalCodeModal.tsx
  src/components/operatorRequest/ProgressBar.tsx
  src/components/operatorRequest/StepOne.tsx
  src/components/operatorRequest/StepThree.tsx
  src/components/operatorRequest/StepTwo.tsx
  src/components/organisms/section/DetailSection.tsx
  src/components/organisms/section/ReviewSection.tsx
  src/hooks/detailPopUp/usePermissions.ts
  src/hooks/detailPopUp/useToast.ts
  src/hooks/modify/useModifyPopUpInfo.tsx
  src/hooks/mypage/useManagerReportPopUp.tsx
  src/hooks/mypage/useUserReportPopUp.tsx
  src/hooks/report/useReportPopUp.tsx
  src/hooks/report/useReportReview.tsx
  src/hooks/review/useCreateReview.tsx
  src/hooks/useCategorySelector.tsx
  src/hooks/useImageSelector.tsx
  src/navigators/options/PopUpDetailOptions.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/detail/PopUpEditRequestScreen.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/myPage/OperatorRegisterScreen.tsx
  src/pages/myPage/ReviewWriteScreen.tsx
  src/pages/myPage/UserRegisterScreen.tsx
  src/pages/report/ReportScreen.tsx
  src/types/AppNavigatorParamList.ts
  src/types/ImageType.ts
  yarn.lock
Labels: ✨ feature ✨, 🎨refactor🎨, 👨🏻‍💻도형👨🏻‍💻

#72 ❗Bug - 캘린더 BottomSheet 버그 수정 (#71)
  ios/Podfile.lock
  ios/PoppinProject/Info.plist
  src/apis/myPage/getUserSetting.ts
  src/apis/myPage/putChangeProfileImage.ts
  src/assets/icons/sign/kakaoCircle.svg
  src/assets/icons/social_login/kakaoButton.png
  src/assets/images/defaultProfile.svg
  src/assets/png/appleCircle.png
  src/assets/png/googleCircle.png
  src/assets/png/kakaoCircle.png
  src/assets/png/naverCircle.png
  src/assets/png/poppinCircle.png
  src/components/ConfirmationModal.tsx
  src/components/CustomOKModal.tsx
  src/components/OperationCalendarBottomSheet.tsx
  src/components/OperationHoursBottomSheet.tsx
  src/components/TextInputWithSvgIconInRight.tsx
  src/components/atoms/toast/ToastComponent.tsx
  src/components/findPopup/CategorySelectButton.tsx
  src/components/findPopup/NotList.tsx
  src/components/operatorRequest/StepTwo.tsx
  src/hooks/detailPopUp/useAddInterestPopUp.tsx
  src/hooks/login/useKakaoLogin.tsx
  src/hooks/myPage/useGetUserSetting.tsx
  src/hooks/myPage/usePutChangeProfileImage.tsx
  src/hooks/myPage/usePutSetting.tsx
  src/hooks/useCategorySelector.tsx
  src/navigators/AppNavigator.tsx
  src/navigators/options/MyPagePreferenceSettingOptions.tsx
  src/navigators/options/ProfileEditOptions.tsx
  src/navigators/options/SignUpPreferenceSettingOptions.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/detail/PopUpEditRequestScreen.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/tab/ClosedTab.tsx
  src/pages/find/tab/NotyetTab.tsx
  src/pages/find/tab/OperatonTab.tsx
  src/pages/likes/LikesScreen.tsx
  src/pages/myPage/FAQFormScreen.tsx
  src/pages/myPage/FAQScreen.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/myPage/PasswordChangeScreen.tsx
  src/pages/myPage/PolicyScreen.tsx
  src/pages/myPage/ProfileEditScreen.tsx
  src/pages/myPage/UserRegisterScreen.tsx
  src/pages/myPage/preferenceSetting/PreferenceSettingScreen.tsx
  src/styles/texts/label/Text12M.ts
  src/types/AppNavigatorParamList.ts
Labels: ✨ feature ✨, 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻

#77 🎨Refactor: 3차 QA전 버그 수정 및 리팩토링 진행
  ios/PoppinProject.xcodeproj/project.pbxproj
  ios/PoppinProject/Info.plist
  package-lock.json
  package.json
  src/assets/detail/sorting.svg
  src/components/PreferenceOptionButtons.tsx
  src/components/alarm/SettingSwitch.tsx
  src/components/atoms/button/OptionSingleButton.tsx
  src/components/atoms/toast/ToastComponent.tsx
  src/components/findPopup/CategorySelectButton.tsx
  src/components/findPopup/FindCard.tsx
  src/components/findPopup/NotList.tsx
  src/components/findPopup/constants.ts
  src/components/molecules/card/InterestPopUpCard.tsx
  src/components/operatorRequest/StepThree.tsx
  src/components/operatorRequest/StepTwo.tsx
  src/components/organisms/header/HomeHeader.tsx
  src/hooks/detailPopUp/useAddInterestPopUp.tsx
  src/hooks/detailPopUp/useDeleteInterestPopUp.tsx
  src/hooks/detailPopUp/useToast.ts
  src/hooks/findPopUp/useGetFindPopupList.tsx
  src/hooks/findPopUp/usePostBookmarkPopup.tsx
  src/hooks/useCategorySelector.tsx
  src/navigators/AppNavigator.tsx
  src/pages/alarm/AlaramSettingScreen.tsx
  src/pages/alarm/tab/PopupTab.tsx
  src/pages/detail/PopUpDetailScreen.tsx
  src/pages/find/FindScreen.tsx
  src/pages/find/FindTab.tsx
  src/pages/find/tab/ClosedTab.tsx
  src/pages/find/tab/NotyetTab.tsx
  src/pages/find/tab/OperatonTab.tsx
  src/pages/home/HomeScreen.tsx
  src/pages/likes/LikesScreen.tsx
  src/pages/likes/ListView.tsx
  src/pages/likes/NoSavedPopupComponent.tsx
  src/pages/likes/calendar/BottomSheetItem.tsx
  src/pages/likes/calendar/CalendarComponent.tsx
  src/pages/likes/calendar/FullCalendarComponent.tsx
  src/pages/myPage/MyPageScreen.tsx
  src/pages/myPage/OperatorRegisterScreen.tsx
  src/pages/myPage/ReviewWriteScreen.tsx
  src/pages/myPage/UserRegisterScreen.tsx
  src/redux/slices/interestedPopUpSlice.ts
  src/redux/stores/reducer.ts
  src/styles/color/globalColors.ts
  src/types/PopUpListData.ts
  src/utils/function/calculateDaysRemaining.tsx
  src/utils/function/permissionUtil.ts
  yarn.lock
Labels: ✨ feature ✨, 🐛bug🐛, 🎨refactor🎨, 👨🏻‍💻도형👨🏻‍💻
