Repository proj-poppin/poppin-app, pull requests merged in 2025-01, with the labels that each got.

#116 Feature/#112 - 프로필 수정 기능 구현 및 후기 작성 완료 리스트 및 후기 자세히 보기 기능 구현
  ios/Podfile.lock
  ios/PoppinProject.xcodeproj/project.pbxproj
  ios/PoppinProject.xcodeproj/xcshareddata/xcschemes/Develop.xcscheme
  ios/PoppinProject.xcodeproj/xcshareddata/xcschemes/PoppinProject.xcscheme
  package.json
  src/Axios/Mypage/mypage.get.axios.ts
  src/Axios/Mypage/mypage.patch.axios.ts
  src/Axios/Mypage/mypage.post.axios.ts
  src/Axios/Mypage/mypage.put.axios.ts
  src/Axios/axios.core.ts
  src/Component/MyPage/Review/Mypage.complete.review.poupupCard.tsx
  src/Component/View/ScreenHeader.component.tsx
  src/Navigator/App.stack.navigator.tsx
  src/Resource/svg/check-blue-icon.svg
  src/Resource/svg/check-icon.svg
  src/Resource/svg/filter.svg
  src/Resource/svg/modal-check-icon.svg
  src/Resource/svg/x-icon.svg
  src/Schema/User/user.schema.ts
  src/Screen/MyPage/Landing/Section/MyPage.landing.review.section.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.profile.section.tsx
  src/Screen/MyPage/Profile/Mypage.password.change.container.tsx
  src/Screen/MyPage/Profile/Mypage.password.change.context.tsx
  src/Screen/MyPage/Profile/Mypage.password.change.modal.tsx
  src/Screen/MyPage/Profile/Mypage.password.change.screen.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.container.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.context.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.modal.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.screen.tsx
  src/Screen/MyPage/Review/Mypage.complete.review.list.container.tsx
  src/Screen/MyPage/Review/Mypage.complete.review.list.context.tsx
  src/Screen/MyPage/Review/Mypage.complete.review.list.detail.screen.tsx
  src/Screen/MyPage/Review/Mypage.complete.review.list.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.detail.container.tsx
  src/Screen/MyPage/Review/Mypage.review.detail.context.tsx
  src/Screen/MyPage/Review/Mypage.review.detail.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.list.container.tsx
  src/Screen/MyPage/Review/Mypage.review.screen.tsx
  src/Screen/Popup/Detail/Provider/Popup.detail.provider.tsx
  src/Screen/Popup/Landing/Popup.landing.zustand.ts
  src/Screen/Popup/Review/Popup.detail.review.write.screen.tsx
  src/Util/date.util.ts
  src/hooks/password/useResetPasswordNonPublic.tsx
  yarn.lock
Labels: ✨ feature ✨, 🐛bug🐛, 🎨refactor🎨, 👨🏻‍💻규진👨🏻‍💻

#128 🎨Refactor - CustomBottomSheet 리팩토링 및 적용 & Calendar UI/UX 개선 & 전역 Modal 관리 시스템 추가
  ios/Podfile.lock
  src/App.tsx
  src/App/App.modal.tsx
  src/App/Modal/App.requiredLogin.modal.tsx
  src/Axios/Mypage/mypage.get.axios.ts
  src/Component/BottomSheet/Age/AgeChooseBottomSheet.tsx
  src/Component/BottomSheet/CustomBottomSheet.tsx
  src/Component/Modal/CommonModal.component.tsx
  src/Component/Modal/CustomModal.tsx
  src/Component/Modal/Popup.category.modal.tsx
  src/Component/Modal/index.ts
  src/Component/MyPage/Report/ReportStepThree.tsx
  src/Component/MyPage/Report/ReportStepTwo.tsx
  src/Navigator/App.stack.navigator.tsx
  src/Screen/MyPage/Landing/Section/MyPage.landing.report.section.tsx
  src/Screen/MyPage/Landing/Section/MyPage.landing.review.section.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.menu.section.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.profile.section.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.container.tsx
  src/Screen/MyPage/Report/Mypage.report.screen.tsx
  src/Screen/MyPage/Request/Operator/Mypage.report.operator.zustand.ts
  src/Screen/MyPage/Request/User/Mypage.report.user.screen.tsx
  src/Screen/MyPage/Request/User/Mypage.report.user.zustand.ts
  src/Screen/MyPage/Review/Mypage.complete.review.list.container.tsx
  src/Screen/MyPage/Review/Mypage.complete.review.list.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.list.container.tsx
  src/Screen/MyPage/Review/Mypage.review.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.visited.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.write.context.tsx
  src/Screen/Popup/Landing/Popup.landing.screen.tsx
  src/Screen/PopupLikes/Landing/InterestedPopupCalendarSection.tsx
  src/Util/axios.util.ts
  src/Util/date.util.ts
  src/Util/local.util.ts
  src/Zustand/App/app.zustand.ts
Labels: 💄ui/ux💄, ✨ feature ✨, 👨🏻‍💻규진👨🏻‍💻

#134 🐛Fix - 구글 & 카카오 로그인 에러 픽스
  src/Component/Button/GoogleLoginButton.tsx
  src/Component/Popup/Landing/PopupStoreCard.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.image.section.tsx
Labels: 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻

#127 🐛Fix - 2차 배포 QA 버그 수정
  src/Axios/Review/review.post.axios.ts
  src/Axios/User/user.post.axios.ts
  src/Component/BottomSheet/CustomBottomSheetButton.tsx
  src/Component/SvgWithNameBoxLabel.tsx
  src/Component/findPopup/NotList.tsx
  src/Resource/svg/filtered-no-result-popup-dot.svg
  src/Resource/svg/review-like-icon.svg
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.zustand.tsx
  src/Screen/MyPage/Review/Mypage.review.normal.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.write.context.tsx
  src/Screen/Popup/Detail/Provider/Popup.detail.review.provider.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.icon.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
  src/Screen/Popup/Landing/Popup.landing.screen.tsx
Labels: 🐛bug🐛, 👩🏻‍💻희진👩🏻‍💻

#138 ✨Feature - 마이페이지 후기 작성 후 숫자 처리 & 제보하기 취소 모달 & 키워드 알림 설정 기능 추가
  ios/Podfile.lock
  src/App/App.modal.tsx
  src/App/Modal/App.popupReportCancel.modal.tsx
  src/Axios/Mypage/mypage.delete.axios.ts
  src/Axios/Mypage/mypage.get.axios.ts
  src/Axios/Mypage/mypage.post.axios.ts
  src/Axios/Mypage/mypage.put.axios.ts
  src/Navigator/App.stack.navigator.tsx
  src/Screen/Auth/Preference/Auth.preference.screen.tsx
  src/Screen/MyPage/KeywordAlarm/Mypage.keywordAlarm.container.tsx
  src/Screen/MyPage/KeywordAlarm/Mypage.keywordAlarm.context.tsx
  src/Screen/MyPage/KeywordAlarm/Mypage.keywordAlarm.screen.tsx
  src/Screen/MyPage/KeywordAlarmScreen.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.menu.section.tsx
  src/Screen/MyPage/PolicyScreen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.screen.tsx
  src/Screen/MyPage/ProfileEditScreen.tsx
  src/Screen/MyPage/Report/Mypage.report.screen.tsx
  src/Screen/MyPage/Request/Operator/Mypage.report.operator.zustand.ts
  src/Screen/MyPage/Request/User/Mypage.report.user.zustand.ts
  src/Screen/MyPage/Review/Mypage.review.normal.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.visited.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.write.context.tsx
  src/Zustand/App/app.zustand.ts
Labels: ✨ feature ✨, 👨🏻‍💻규진👨🏻‍💻

#141 🐛Fix - 2차 QA 버그 해결 (키워드 알림 설정 , 리뷰 중복 작성, 상세 페이지 -> 방문 팝업 후기 라우팅)
  src/Screen/MyPage/Landing/Section/Mypage.landing.menu.section.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.recentPopup.section.tsx
  src/Screen/MyPage/Review/Mypage.review.write.context.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
Labels: 🐛bug🐛, 🎨refactor🎨, 👨🏻‍💻규진👨🏻‍💻

#143 🐛Fix - 취향 설정 관련 버그 해결, 건너뛰기 버튼 활성화, 리뷰 신고 기능 활성화
  src/Axios/User/user.post.axios.ts
  src/Component/Button/AppleLoginButton.tsx
  src/Component/Button/GoogleLoginButton.tsx
  src/Component/Button/KakaoLoginButton.tsx
  src/Component/Button/NaverLoginButton.tsx
  src/Component/Modal/Auth.preference.skip.modal.tsx
  src/Component/View/ScreenHeader.component.tsx
  src/Navigator/App.stack.navigator.tsx
  src/Screen/Auth/Landing/Auth.landing.Screen.tsx
  src/Screen/Auth/Preference/Auth.preference.screen.tsx
  src/Screen/Auth/Preference/Auth.preference.zustand.tsx
  src/Screen/Home/Landing/Home.landing.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.zustand.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
  src/Screen/Splash/LoadingScreen.tsx
  src/Zustand/Popup/popup.zustand.ts
Labels: 🐛bug🐛, 👩🏻‍💻희진👩🏻‍💻

#146 🐛Fix - 2차 QA 이후 버그 수정 (2) - 비회원 로그인 유도 모달, 마이페이지 - 문의하기 /FAQ 링킹 추가
  src/Component/Popup/Landing/PopupStoreCard.tsx
  src/Screen/Home/Landing/Section/Home.landing.screenHeader.tsx
  src/Screen/MyPage/Landing/MyPageLandingScreen.tsx
  src/Screen/MyPage/Landing/Section/Mypage.landing.menu.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.button.row.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.icon.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
  src/Zustand/App/app.zustand.ts
Labels: 🐛bug🐛, 👨🏻‍💻규진👨🏻‍💻

#151 🐛Fix - 공유하기, 공지 알림 접속시 redirect 로직 개선 및 후기 작성시 라우팅 개선
  ios/Podfile.lock
  src/Axios/Popup/popup.get.axios.ts
  src/Axios/User/user.patch.axios.ts
  src/Component/MyPage/Notification.listItem.component.tsx
  src/Navigator/App.stack.navigator.tsx
  src/Schema/User/userNotificationSetting.schema.ts
  src/Screen/App/KakaoLink/App.kakaoLink.screen.tsx
  src/Screen/Auth/Landing/Auth.landing.Screen.tsx
  src/Screen/Home/Landing/Home.landing.screen.tsx
  src/Screen/Home/Landing/Section/Home.landing.screenHeader.tsx
  src/Screen/Popup/Detail/Provider/Popup.detail.provider.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.icon.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
  src/Screen/Splash/Splash.screen.provider.tsx
  src/Screen/Splash/Splash.screen.tsx
  src/Segment/Notification/notificationButton.segment.tsx
  src/Util/navigation.util.ts
  src/Zustand/Popup/popup.zustand.ts
  src/Zustand/User/notification.zustand.ts
  yarn.lock
Labels: 🐛bug🐛, 👨🏻‍💻도형👨🏻‍💻
