Repository proj-poppin/poppin-app, pull requests merged in 2025-02, with the labels that each got.

#154 🐛Fix - 방문하기 버튼 클릭 후 마이페이지의 후기 작성하기 아래 숫자 로직 변경
  src/Component/Button/GoogleLoginButton.tsx
  src/Screen/MyPage/Review/Mypage.review.list.container.tsx
  src/Screen/MyPage/Review/Mypage.review.list.context.tsx
  src/Screen/Popup/Detail/Provider/Popup.detail.provider.tsx
Labels: 🐛bug🐛, 👩🏻‍💻희진👩🏻‍💻

#159 🐛Fix - 팝업 찾기, 취향 설정, 관심 팝업 관련 QA
  ios/Podfile.lock
  package.json
  src/Component/Popup/Landing/PopupStoreCard.tsx
  src/Component/YearMonthPicker.tsx
  src/Resource/svg/calendar-top-arrow-blue-icon.svg
  src/Resource/svg/star-with-bottom-shadow-icon.svg
  src/Screen/Auth/Preference/Auth.preference.zustand.tsx
  src/Screen/Home/Landing/Home.landing.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.zustand.tsx
  src/Screen/PopupLikes/Landing/InterestedPopupCalendarSection.tsx
  src/Screen/PopupLikes/Landing/PopupLikes.landing.screen.tsx
  src/Screen/PopupLikes/Landing/PopupLikes.landing.zustand.ts
  yarn.lock
Labels: ✨ feature ✨, 🐛bug🐛, 👩🏻‍💻희진👩🏻‍💻

#158 🐛Fix - 2차 QA 이슈 해결 (1)
  src/Screen/MyPage/Review/Mypage.review.normal.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.screen.tsx
  src/Screen/Popup/Detail/Provider/Popup.detail.provider.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.button.row.section.tsx
  src/Screen/Popup/Detail/Section/Popup.detail.review.section.tsx
  src/Zustand/Popup/popup.zustand.ts
Labels: 🐛bug🐛, 👨🏻‍💻은상👨🏻‍💻

#165 🐛Fix - 팝업 찾기 무한스크롤 버그 픽스, YearMonthPicker 디자인 보완
  src/Component/Modal/CommonModal.component.tsx
  src/Component/YearMonthPicker.tsx
  src/Screen/Popup/Landing/Popup.landing.screen.tsx
Labels: 💄ui/ux💄, 🐛bug🐛, 👩🏻‍💻희진👩🏻‍💻

#167 ✨Feature - Debouncing 을 이용해 Searching 관련 UX 최적화
  .github/CODEOWNERS
  .github/workflows/build.yml
  .watchmanconfig
  .yarn/releases/yarn-3.6.4.cjs
  .yarnrc.yml
  ios/Podfile.lock
  src/App/App.modal.tsx
  src/Component/Modal/Popup.category.modal.tsx
  src/Component/MyPage/Review/Mypage.review.searchBar.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Screen/MyPage/Policy/Mypage.policy.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.screen.tsx
  src/Screen/MyPage/PreferenceSetting/Mypage.preferenceSetting.zustand.tsx
  src/Screen/MyPage/PreferenceSetting/PreferenceSettingScreen.tsx
  src/Screen/MyPage/PreferenceSetting/types.ts
  src/Screen/MyPage/Profile/Mypage.password.change.container.tsx
  src/Screen/MyPage/Profile/Mypage.password.change.context.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.container.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.context.tsx
  src/Screen/MyPage/Profile/Mypage.profile.edit.screen.tsx
  src/Screen/MyPage/Request/Operator/Mypage.report.operator.screen.tsx
  src/Screen/MyPage/Review/Mypage.review.normal.screen.tsx
  src/Screen/Popup/Landing/Popup.landing.screen.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ feature ✨, 👨🏻‍💻규진👨🏻‍💻
